# https://alacritty.org

# Customizations

cursor:
  style:
    shape: Underline # Block, Underline, Beam
font:
  normal:
    family: Hack Nerd Font
  size: 12
window:
  opacity: 0.7

# Theme: Ayu Dark
# https://github.com/alacritty/alacritty/wiki/Color-schemes

colors:
  # Default colors
  primary:
    background: "#0A0E14"
    foreground: "#B3B1AD"

  # Normal colors
  normal:
    black: "#01060E"
    red: "#EA6C73"
    green: "#91B362"
    yellow: "#F9AF4F"
    blue: "#53BDFA"
    magenta: "#FAE994"
    cyan: "#90E1C6"
    white: "#C7C7C7"

  # Bright colors
  bright:
    black: "#686868"
    red: "#F07178"
    green: "#C2D94C"
    yellow: "#FFB454"
    blue: "#59C2FF"
    magenta: "#FFEE99"
    cyan: "#95E6CB"
    white: "#FFFFFF"
