# https://alacritty.org

[general]
import = [
  # "~/.config/alacritty/themes/themes/everforest_dark.toml",
  # "~/.config/alacritty-theme/themes/everforest_light.toml",

  # "~/.config/alacritty-theme/themes/catppuccin_frappe.toml",
  # "~/.config/alacritty-theme/themes/catppuccin_latte.toml",
]

[cursor.style]
shape = "Underline"

[font]
size = 16

[font.normal]
family = "Hack Nerd Font"
style = "Bold"

[window]
opacity = 0.8

# [[keyboard.bindings]]
# chars = """
# clear
# """
# key = "L"
# mods = "Control"
